apiVersion: v1
kind: Service
metadata:
  name: assessment-balancer
spec:
  selector:
    app: assessment
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment
spec:
  selector:
    matchLabels:
      app: assessment
  replicas: 4
  template:
    metadata:
      labels:
        app: assessment
    spec:
      containers:
      - name: assessment
        image: al-assessment2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000